language: android

install: true

sudo: true

notifications:
  email: false

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # BuildTools version used by project
    - build-tools-28.0.3

    # SDK version to compile project
    - android-28

script:
  - ./gradlew build
  - ./gradlew :app:ktlintCheck
  - ./gradlew :app:lint
  - bundle install
  - bundle exec danger

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
    - ".gradle"
