name: CI

on:
  pull_request:
    paths:
      - .github/workflows/pr-checker.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew :app:lintDebug
      - name: Install gem blunder
        run: sudo gem install bundler:1.17.1
      - name: Run bundle
        run: bundle install
      - name: Execute Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger